# Generated by Django 5.1.6 on 2025-03-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('CardNumber', models.IntegerField()),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
