# Generated by Django 5.1.6 on 2025-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('FullName', models.CharField(max_length=100)),
                ('CardNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('inventory', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
