# Generated by Django 5.1.6 on 2025-03-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
